const Images = [
  {
    id: 1,
    img: "images/fantasticfour_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/fantastic-four",
    title: "Fantastic Four",
  },
  {
    id: 2,
    img: "images/antman_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/ant-man-and-the-wasp-quantumania",
    title: "Ant-Man and Wasp:quantumania",
  },
  {
    id: 3,
    img: "images/blade_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/blade",
    title: "Blade",
  },
  {
    id: 4,
    img: "images/themarvels_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/the-marvels",
    title: "The Marvels",
  },
  {
    id: 5,
    img: "images/blackpanther2_lob_crd_02.jpg",
    link: "https://www.marvel.com/movies/black-panther-wakanda-forever",
    title: "Black Panther: Wakanda Forever",
  },
  {
    id: 6,
    img: "images/thorloveandthunder_lob_crd_02.jpg",
    link: "https://www.marvel.com/movies/thor-love-and-thunder",
    title: "Thor: Love and Thunder",
  },
  {
    id: 7,
    img: "images/ds2_card_1.jpg",
    link: "https://www.marvel.com/movies/doctor-strange-in-the-multiverse-of-madness",
    title: "Doctor Strange in the Multiverse of Madness",
  },
  {
    id: 8,
    img: "images/spider-mannowayhome_lob_crd_02.jpg",
    link: "https://www.marvel.com/movies/spider-man-no-way-home",
    title: "Spider-Man: No Way Home",
  },
  {
    id: 9,
    img: "images/eternals_lob_crd_03_0.jpg",
    link: "https://www.marvel.com/movies/eternals",
    title: "Eternals",
  },
  {
    id: 10,
    img: "images/shangchi_lob_crd_07.jpg",
    link: "https://www.marvel.com/movies/shang-chi-and-the-legend-of-the-ten-rings",
    title: "Shang-Chi and The Legend of The Rings",
  },
  {
    id: 11,
    img: "images/blackwidow_lob_crd_06.jpg",
    link: "https://www.marvel.com/movies/black-widow",
    title: "Blackwidow",
  },
  {
    id: 12,
    img: "images/spider-manfarfromhome_lob_crd_04_3.jpg",
    link: "https://www.marvel.com/movies/spider-man-far-from-home",
    title: "Spider-Man: Far From Home",
  },
  {
    id: 13,
    img: "images/avengersendgame_lob_crd_05_2.jpg",
    link: "https://www.marvel.com/movies/avengers-endgame",
    title: "Avengers : Endgame",
  },
  {
    id: 14,
    img: "images/captainmarvel_lob_crd_06.jpg",
    link: "https://www.marvel.com/movies/captain-marvel",
    title: "Captain Marvel",
  },
  {
    id: 15,
    img: "images/ant-manthewasp_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/ant-man-and-the-wasp",
    title: "Ant-Man and Wasp",
  },
  {
    id: 16,
    img: "images/avengersinfinitywar_lob_crd_02_1.jpg",
    link: "https://www.marvel.com/movies/avengers-infinity-war",
    title: "Avengers : Infinity War",
  },
  {
    id: 17,
    img: "images/blackpanther_lob_crd_01_4.jpg",
    link: "https://www.marvel.com/movies/black-panther",
    title: "Black Panther",
  },
  {
    id: 18,
    img: "images/thorragnarok_lob_crd_03.jpg",
    link: "https://www.marvel.com/movies/thor-ragnarok",
    title: "Thor : Rangnarok",
  },
  {
    id: 19,
    img: "images/spider-manhomecoming_lob_crd_01_3.jpg",
    link: "https://www.marvel.com/movies/spider-man-homecoming",
    title: "Spider-Man : Homecoming",
  },
  {
    id: 20,
    img: "images/guardiansofthegalaxyvol.2_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/guardians-of-the-galaxy-vol-2",
    title: "Gardians Of Galaxy vol.2",
  },
  {
    id: 21,
    img: "images/doctorstrange_lob_crd_01_6.jpg",
    link: "https://www.marvel.com/movies/doctor-strange",
    title: "Doctor Strange",
  },
  {
    id: 22,
    img: "images/captainamericacivilwar_lob_crd_01_9.jpg",
    link: "https://www.marvel.com/movies/captain-america-civil-war",
    title: "Captain America: Civilwar",
  },
  {
    id: 23,
    img: "images/ant-man_lob_crd_01_8.jpg",
    link: "https://www.marvel.com/movies/ant-man",
    title: "Ant-Man",
  },
  {
    id: 24,
    img: "images/avengersageofultron_lob_crd_03.jpg",
    link: "https://www.marvel.com/movies/avengers-age-of-ultron",
    title: "Avengers: Age Of Ultron",
  },
  {
    id: 25,
    img: "images/guardiansofthegalaxy_lob_crd_03.jpg",
    link: "https://www.marvel.com/movies/guardians-of-the-galaxy",
    title: "Gardian Of Galaxy",
  },
  {
    id: 26,
    img: "images/captainamericathewintersoldier_lob_crd_01_1.jpg",
    link: "https://www.marvel.com/movies/captain-america-the-winter-soldier",
    title: "Captain America: Winter Soldier",
  },
  {
    id: 27,
    img: "images/thorthedarkworld_lob_crd_02_1.jpg",
    link: "https://www.marvel.com/movies/thor-the-dark-world",
    title: "Thor: The Dark World",
  },
  {
    id: 28,
    img: "images/ironman3_lob_crd_01_10.jpg",
    link: "https://www.marvel.com/movies/iron-man-3",
    title: "Iron Man 3",
  },
  {
    id: 29,
    img: "images/theavengers_lob_crd_03.jpg",
    link: "https://www.marvel.com/movies/the-avengers",
    title: "The Avengers",
  },
  {
    id: 30,
    img: "images/captainamerica_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/captain-america-the-first-avenger",
    title: "Captain America: First Avenger",
  },
  {
    id: 31,
    img: "images/thor_lob_crd_01.jpg",
    link: "https://www.marvel.com/movies/thor",
    title: "Thor",
  },
  {
    id: 32,
    img: "images/ironman2_lob_crd_01_3.jpg",
    link: "https://www.marvel.com/movies/iron-man-2",
    title: "Iron Man 2",
  },
  {
    id: 33,
    img: "images/theincrediblehulk_lob_crd_01_2.jpg",
    link: "https://www.marvel.com/movies/the-incredible-hulk",
    title: "The Incredible Hulk",
  },
  {
    id: 34,
    img: "images/ironman_lob_crd_01_3.jpg",
    link: "https://www.marvel.com/movies/iron-man",
    title: "Iron Man",
  },
];

export default Images;
